version: "3.4"

services:
    php:
        container_name: invisio-php
        build:
            context: ./docker/php-fpm
        ports:
            - '9000:9000'
        volumes:
            - ./:/var/www/symfony

    nginx:
        container_name: invisio-nginx
        image: nginx:stable-alpine
        ports:
            - '8080:80'
        volumes:
            - ./:/var/www/symfony
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php